--OPTIONS(DIRECT=TRUE)
LOAD DATA
INTO TABLE coimsett
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(ID_SETTORE                    CHAR(20) NULLIF (ID_SETTORE = BLANKS) "RTRIM(:ID_SETTORE)"
,DESCRIZIONE                   CHAR(50) NULLIF (DESCRIZIONE = BLANKS) "RTRIM(:DESCRIZIONE)"
,RESPONSABILE                  CHAR(10) NULLIF (RESPONSABILE = BLANKS) "RTRIM(:RESPONSABILE)"
)
