--OPTIONS(DIRECT=TRUE)
LOAD DATA
INTO TABLE coimtpdo
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_TPDO                      CHAR(8) NULLIF (COD_TPDO = BLANKS) "RTRIM(:COD_TPDO)"
,DESCRIZIONE                   CHAR(50) NULLIF (DESCRIZIONE = BLANKS) "RTRIM(:DESCRIZIONE)"
,FLAG_MODIFICA                 CHAR(1) NULLIF (FLAG_MODIFICA = BLANKS)
)
