--OPTIONS(DIRECT=TRUE)
LOAD DATA
INTO TABLE coimanrg
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_TANO                      CHAR(8) NULLIF (COD_TANO = BLANKS) "RTRIM(:COD_TANO)"
,COD_RGEN                      CHAR(8) NULLIF (COD_RGEN = BLANKS) "RTRIM(:COD_RGEN)"
)
