--OPTIONS(DIRECT=TRUE)
LOAD DATA
INTO TABLE coimtari
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(TIPO_COSTO                    DECIMAL EXTERNAL(9) NULLIF (TIPO_COSTO = BLANKS)
,COD_POTENZA                   CHAR(8) NULLIF (COD_POTENZA = BLANKS) "RTRIM(:COD_POTENZA)"
,DATA_INIZIO                   DATE(10) "YYYY-MM-DD" NULLIF (DATA_INIZIO = BLANKS)
,IMPORTO                       DECIMAL EXTERNAL(11) NULLIF (IMPORTO = BLANKS)
)
