--OPTIONS(DIRECT=TRUE)
LOAD DATA
INTO TABLE coimtdoc
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(TIPO_DOCUMENTO                CHAR(2) NULLIF (TIPO_DOCUMENTO = BLANKS) "RTRIM(:TIPO_DOCUMENTO)"
,DESCRIZIONE                   CHAR(100) NULLIF (DESCRIZIONE = BLANKS) "RTRIM(:DESCRIZIONE)"
,FLAG_MODIFICA                 CHAR(1) NULLIF (FLAG_MODIFICA = BLANKS)
)
