--OPTIONS(DIRECT=TRUE)
LOAD DATA
INTO TABLE coimmenp
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(NOME_MENU                     CHAR(20) NULLIF (NOME_MENU = BLANKS) "RTRIM(:NOME_MENU)"
,DESCRIZIONE                   CHAR(60) NULLIF (DESCRIZIONE = BLANKS) "RTRIM(:DESCRIZIONE)"
)
