--OPTIONS(DIRECT=TRUE)
LOAD DATA
INTO TABLE coimenrg
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_RGEN                      CHAR(8) NULLIF (COD_RGEN = BLANKS) "RTRIM(:COD_RGEN)"
,COD_ENRE                      CHAR(8) NULLIF (COD_ENRE = BLANKS) "RTRIM(:COD_ENRE)"
)
