--OPTIONS(DIRECT=TRUE)
LOAD DATA
INTO TABLE coimtopo
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_TOPO                      CHAR(8) NULLIF (COD_TOPO = BLANKS) "RTRIM(:COD_TOPO)"
,DESCR_TOPO                    CHAR(50) NULLIF (DESCR_TOPO = BLANKS) "RTRIM(:DESCR_TOPO)"
)
