--OPTIONS(DIRECT=TRUE)
LOAD DATA
INTO TABLE coimruol
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(ID_RUOLO                      CHAR(20) NULLIF (ID_RUOLO = BLANKS) "RTRIM(:ID_RUOLO)"
,DESCRIZIONE                   CHAR(50) NULLIF (DESCRIZIONE = BLANKS) "RTRIM(:DESCRIZIONE)"
)
