--OPTIONS(DIRECT=TRUE)
LOAD DATA
INTO TABLE coimlist
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_LISTINO                   CHAR(8) NULLIF (COD_LISTINO = BLANKS) "RTRIM(:COD_LISTINO)"
,DESCRIZIONE                   CHAR(50) NULLIF (DESCRIZIONE = BLANKS) "RTRIM(:DESCRIZIONE)"
)
