--OPTIONS(DIRECT=TRUE)
LOAD DATA
INTO TABLE coimrgen
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_RGEN                      CHAR(8) NULLIF (COD_RGEN = BLANKS) "RTRIM(:COD_RGEN)"
,DESCRIZIONE                   CHAR(100) NULLIF (DESCRIZIONE = BLANKS) "RTRIM(:DESCRIZIONE)"
)
