@ 0-coim-unload/unload/coim_as_resp
@ 0-coim-unload/unload/coimaces
@ 0-coim-unload/unload/coimacts
@ 0-coim-unload/unload/coimaimp
@ 0-coim-unload/unload/coimalim
@ 0-coim-unload/unload/coimanec
@ 0-coim-unload/unload/coimanom
@ 0-coim-unload/unload/coimanrg
@ 0-coim-unload/unload/coimarea
@ 0-coim-unload/unload/coimbatc
@ 0-coim-unload/unload/coimboap
@ 0-coim-unload/unload/coimboll
@ 0-coim-unload/unload/coimbpos
@ 0-coim-unload/unload/coimcaus
@ 0-coim-unload/unload/coimcimp
@ 0-coim-unload/unload/coimcinc
@ 0-coim-unload/unload/coimcitt
@ 0-coim-unload/unload/coimcitt_st
@ 0-coim-unload/unload/coimcmar
@ 0-coim-unload/unload/coimcoma
@ 0-coim-unload/unload/coimcomb
@ 0-coim-unload/unload/coimcomu
@ 0-coim-unload/unload/coimcont
@ 0-coim-unload/unload/coimcost
@ 0-coim-unload/unload/coimcout
--@ 0-coim-unload/unload/coimcqua
@ 0-coim-unload/unload/coimcted
--@ 0-coim-unload/unload/coimcuar
--@ 0-coim-unload/unload/coimcurb
@ 0-coim-unload/unload/coimdesc
@ 0-coim-unload/unload/coimdest
@ 0-coim-unload/unload/coimdimp
@ 0-coim-unload/unload/coimdist
@ 0-coim-unload/unload/coimdmsg
select 'tabella coimdocu non scaricata: blob' from dual;
--@ 0-coim-unload/unload/coimdocu
@ 0-coim-unload/unload/coimenre
@ 0-coim-unload/unload/coimenrg
@ 0-coim-unload/unload/coimenti
@ 0-coim-unload/unload/coimenve
@ 0-coim-unload/unload/coimesit
@ 0-coim-unload/unload/coimfatt
@ 0-coim-unload/unload/coimfdc
@ 0-coim-unload/unload/coimflre
@ 0-coim-unload/unload/coimfuge
@ 0-coim-unload/unload/coimfunp
@ 0-coim-unload/unload/coimfunz
@ 0-coim-unload/unload/coimgage
@ 0-coim-unload/unload/coimgend
@ 0-coim-unload/unload/coimgend_as_resp
@ 0-coim-unload/unload/coimgend_st
@ 0-coim-unload/unload/coiminco
@ 0-coim-unload/unload/coiminco_st
@ 0-coim-unload/unload/coimimst
@ 0-coim-unload/unload/coiminst
@ 0-coim-unload/unload/coimlist
@ 0-coim-unload/unload/coimmanu
@ 0-coim-unload/unload/coimmenp
@ 0-coim-unload/unload/coimmenu
@ 0-coim-unload/unload/coimmode
@ 0-coim-unload/unload/coimmovi
@ 0-coim-unload/unload/coimmtar
@ 0-coim-unload/unload/coimnoveb
@ 0-coim-unload/unload/coimogge
@ 0-coim-unload/unload/coimopdi
@ 0-coim-unload/unload/coimopve
@ 0-coim-unload/unload/coimpote
@ 0-coim-unload/unload/coimprof
@ 0-coim-unload/unload/coimprog
@ 0-coim-unload/unload/coimprov
@ 0-coim-unload/unload/coimprvv
@ 0-coim-unload/unload/coimqrar
@ 0-coim-unload/unload/coimregi
@ 0-coim-unload/unload/coimrelg
@ 0-coim-unload/unload/coimrelt
@ 0-coim-unload/unload/coimrfis
@ 0-coim-unload/unload/coimrgen
@ 0-coim-unload/unload/coimrgh
@ 0-coim-unload/unload/coimrife
@ 0-coim-unload/unload/coimruol
@ 0-coim-unload/unload/coimscamb
@ 0-coim-unload/unload/coimsett
@ 0-coim-unload/unload/coimsrcg
@ 0-coim-unload/unload/coimsrcm
@ 0-coim-unload/unload/coimsrdg
@ 0-coim-unload/unload/coimstat
@ 0-coim-unload/unload/coimstpm
@ 0-coim-unload/unload/coimstrl
@ 0-coim-unload/unload/coimstru
@ 0-coim-unload/unload/coimstub
@ 0-coim-unload/unload/coimtano
@ 0-coim-unload/unload/coimtari
@ 0-coim-unload/unload/coimtcar
@ 0-coim-unload/unload/coimtdoc
@ 0-coim-unload/unload/coimtipo_grup_termico
@ 0-coim-unload/unload/coimtgen
@ 0-coim-unload/unload/coimtmsg
@ 0-coim-unload/unload/coimtodo
@ 0-coim-unload/unload/coimtopo
@ 0-coim-unload/unload/coimtpbo
@ 0-coim-unload/unload/coimtpco
@ 0-coim-unload/unload/coimtpdo
@ 0-coim-unload/unload/coimtpdu
@ 0-coim-unload/unload/coimtpem
@ 0-coim-unload/unload/coimtpes
@ 0-coim-unload/unload/coimtpim
@ 0-coim-unload/unload/coimtpnu
@ 0-coim-unload/unload/coimtppr
@ 0-coim-unload/unload/coimtppt
@ 0-coim-unload/unload/coimtprg
@ 0-coim-unload/unload/coimtpsg
@ 0-coim-unload/unload/coimtrans_manu
@ 0-coim-unload/unload/coimutar
@ 0-coim-unload/unload/coimuten
@ 0-coim-unload/unload/coimutgi
@ 0-coim-unload/unload/coimviae
@ 0-coim-unload/unload/coimviar

