#!/bin/bash

./4-coim-load/load.bat coimaces
./4-coim-load/load.bat coimacts
./4-coim-load/load.bat coimaimp
./4-coim-load/load.bat coimanec
./4-coim-load/load.bat coimanom
./4-coim-load/load.bat coimanrg
./4-coim-load/load.bat coimarea
./4-coim-load/load.bat coimbatc
./4-coim-load/load.bat coimboap
./4-coim-load/load.bat coimboll
./4-coim-load/load.bat coimbpos
./4-coim-load/load.bat coimcaus
./4-coim-load/load.bat coimcimp
./4-coim-load/load.bat coimcinc
./4-coim-load/load.bat coimcitt
./4-coim-load/load.bat coimcmar
./4-coim-load/load.bat coimcoma
./4-coim-load/load.bat coimcomb
./4-coim-load/load.bat coimcomu
./4-coim-load/load.bat coimcont
./4-coim-load/load.bat coimcost
./4-coim-load/load.bat coimcout
#./4-coim-load/load.bat coimcqua
./4-coim-load/load.bat coimcted
#./4-coim-load/load.bat coimcuar
#./4-coim-load/load.bat coimcurb
./4-coim-load/load.bat coimdesc
./4-coim-load/load.bat coimdest
./4-coim-load/load.bat coimdimp
./4-coim-load/load.bat coimdimp_gend
./4-coim-load/load.bat coimdist
./4-coim-load/load.bat coimdmsg
echo 'tabella coimdocu non caricata: blob'
#./4-coim-load/load.bat coimdocu
./4-coim-load/load.bat coimdope_aimp
./4-coim-load/load.bat coimdope_gend
./4-coim-load/load.bat coimenre
./4-coim-load/load.bat coimenrg
./4-coim-load/load.bat coimenti
./4-coim-load/load.bat coimenve
./4-coim-load/load.bat coimesit
./4-coim-load/load.bat coimfatt
./4-coim-load/load.bat coimflre
./4-coim-load/load.bat coimfuge
./4-coim-load/load.bat coimfunp
./4-coim-load/load.bat coimfunz
./4-coim-load/load.bat coimgage
./4-coim-load/load.bat coimgend
./4-coim-load/load.bat coimimst
./4-coim-load/load.bat coiminco
./4-coim-load/load.bat coiminst
./4-coim-load/load.bat coimmanu
./4-coim-load/load.bat coimmenp
./4-coim-load/load.bat coimmenu
./4-coim-load/load.bat coimmode
./4-coim-load/load.bat coimmovi
./4-coim-load/load.bat coimmtar
./4-coim-load/load.bat coimnoveb
./4-coim-load/load.bat coimogge
./4-coim-load/load.bat coimopdi
./4-coim-load/load.bat coimopve
./4-coim-load/load.bat coimpote
./4-coim-load/load.bat coimprof
./4-coim-load/load.bat coimprog
./4-coim-load/load.bat coimprov
./4-coim-load/load.bat coimprvv
./4-coim-load/load.bat coimqrar
./4-coim-load/load.bat coimregi
./4-coim-load/load.bat coimrelg
./4-coim-load/load.bat coimrelt
./4-coim-load/load.bat coimcaus
./4-coim-load/load.bat coimrgen
./4-coim-load/load.bat coimrgh
./4-coim-load/load.bat coimrife
./4-coim-load/load.bat coimruol
./4-coim-load/load.bat coimsett
./4-coim-load/load.bat coimsrcg
./4-coim-load/load.bat coimsrcm
./4-coim-load/load.bat coimsrdg
./4-coim-load/load.bat coimstpm
./4-coim-load/load.bat coimstrl
./4-coim-load/load.bat coimstub
./4-coim-load/load.bat coimtano
./4-coim-load/load.bat coimtari
./4-coim-load/load.bat coimtcar
./4-coim-load/load.bat coimtdoc
./4-coim-load/load.bat coimtgen
./4-coim-load/load.bat coimtmsg
./4-coim-load/load.bat coimtipo_grup_termico
./4-coim-load/load.bat coimtodo
./4-coim-load/load.bat coimtopo
./4-coim-load/load.bat coimtpbo
./4-coim-load/load.bat coimtpco
./4-coim-load/load.bat coimtpdo
./4-coim-load/load.bat coimtpdu
./4-coim-load/load.bat coimtpem
./4-coim-load/load.bat coimtpes
./4-coim-load/load.bat coimtpim
./4-coim-load/load.bat coimtppr
./4-coim-load/load.bat coimtprg
./4-coim-load/load.bat coimtpsg
./4-coim-load/load.bat coimutar
./4-coim-load/load.bat coimuten
./4-coim-load/load.bat coimutgi
./4-coim-load/load.bat coimviae
./4-coim-load/load.bat coimviar
./4-coim-load/load.bat coimlist
