-- tabelle
-- le creo nei segenti tablesapce

\i coim_as_resp.sql
\i coim_d_anom.sql
\i coim_d_clas.sql
\i coim_d_esit.sql
\i coim_d_tano.sql
\i coim_tp_att.sql
\i coimaccu_aimp.sql
\i coimaces.sql
\i coimacts.sql
\i coimadre.sql
\i coimaimp.sql
\i coimaimp_st.sql
\i coimalim.sql
\i coimallegati.sql
\i coimaltr_gend_aimp.sql
\i coimanec.sql
\i coimanom.sql
\i coimanrg.sql
\i coimarea.sql
\i coimbatc.sql
\i coimboap.sql
\i coimboll.sql
\i coimbpos.sql
\i coimcamp_sola_aimp.sql
\i coimcaup.sql
\i coimcaus.sql
\i coimcimp.sql
\i coimcinc.sql
\i coimcind.sql
\i coimcirc_inte_aimp.sql
\i coimcitt.sql
\i coimcitt_st.sql
\i coimcmar.sql
\i coimcoma.sql
\i coimcomb.sql
\i coimcomu.sql
\i coimcont.sql
\i coimcost.sql
\i coimcout.sql
\i coimcqua.sql
\i coimcted.sql
\i coimcuar.sql
\i coimcurb.sql
\i coimdesc.sql
\i coimdimp.sql
\i coimdimp_gend.sql
\i coimdimp_prfumi.sql
\i coimdimp_stn.sql
\i coimdist.sql
\i coimdocu.sql
\i coimdmsg.sql
\i coimdope_aimp.sql
\i coimdope_gend.sql
\i coimenre.sql
\i coimenrg.sql
\i coimenti.sql
\i coimenve.sql
\i coimesit.sql
\i coimfatt.sql
\i coimfdc.sql
\i coimfile_pagamenti_postali.sql
\i coimflre.sql
\i coimfuge.sql
\i coimfunp.sql
\i coimfunz.sql
\i coimgage.sql
\i coimgend.sql
\i coimgend_as_resp.sql
\i coimgend_st.sql
\i coimimst.sql
\i coiminco.sql
\i coiminco_st.sql
\i coiminst.sql
\i coimmanu.sql
\i coimmenp.sql
\i coimmenu.sql
\i coimmode.sql
\i coimmovi.sql
\i coimmtar.sql
\i coimnoveb.sql
\i coimogge.sql
\i coimopdi.sql
\i coimopma.sql
\i coimopve.sql
\i coimparm.sql
\i coimpomp_circ_aimp.sql
\i coimpesi.sql
\i coimpote.sql
\i coimprof.sql
\i coimprog.sql
\i coimprov.sql
\i coimprvv.sql
\i coimqrar.sql
\i coimraff_aimp.sql
\i coimrecu_calo_aimp.sql
\i coimrecu_cond_aimp.sql
\i coimregi.sql
\i coimrelg.sql
\i coimrelt.sql
\i coimrfis.sql
\i coimrgen.sql
\i coimrgh.sql
\i coimrife.sql
\i coimruol.sql
\i coimscam_calo_aimp.sql
\i coimscamb.sql
\i coimsett.sql
\i coimsrcg.sql
\i coimsrcm.sql
\i coimsrdg.sql
\i coimstat.sql
\i coimstpm.sql
\i coimstub.sql
\i coimstrl.sql
\i coimstru.sql
\i coimtabs.sql
\i coimtano.sql
\i coimtari.sql
\i coimtcar.sql
\i coimtdoc.sql
\i coimtgen.sql
\i coimtipo_grup_termico.sql
\i coimtmsg.sql
\i coimtodo.sql
\i coimtopo.sql
\i coimtorr_evap_aimp.sql
\i coimtpbo.sql
\i coimtpco.sql
\i coimtpdo.sql
\i coimtpdu.sql
\i coimtpem.sql
\i coimtpes.sql
\i coimtpim.sql
\i coimtpnu.sql
\i coimtppr.sql
\i coimtppt.sql
\i coimtprg.sql
\i coimtpsg.sql
\i coimtrans_manu.sql
\i coimtrat_aria_aimp.sql
\i coimutar.sql
\i coimuten.sql
\i coimutgi.sql
\i coimvasi_espa_aimp.sql
\i coimvent_aimp.sql
\i coimviae.sql
\i coimviar.sql
\i coimlist.sql
\i coimereg.sql
