sort coimaces.dat -o coimaces.dat
sort coimacts.dat -o coimacts.dat
sort coimaimp.dat -o coimaimp.dat
sort coimanom.dat -o coimanom.dat
sort coimanrg.dat -o coimanrg.dat
sort coimarea.dat -o coimarea.dat
sort coimbatc.dat -o coimbatc.dat
sort coimboll.dat -o coimboll.dat
sort coimcimp.dat -o coimcimp.dat
sort coimcinc.dat -o coimcinc.dat
sort coimcitt.dat -o coimcitt.dat
sort coimcmar.dat -o coimcmar.dat
sort coimcoma.dat -o coimcoma.dat
sort coimcomb.dat -o coimcomb.dat
sort coimcomu.dat -o coimcomu.dat
sort coimcost.dat -o coimcost.dat
sort coimcqua.dat -o coimcqua.dat
sort coimcted.dat -o coimcted.dat
sort coimcuar.dat -o coimcuar.dat
sort coimcurb.dat -o coimcurb.dat
sort coimdesc.dat -o coimdesc.dat
sort coimdimp.dat -o coimdimp.dat
sort coimdist.dat -o coimdist.dat
sort coimdocu.dat -o coimdocu.dat
sort coimenre.dat -o coimenre.dat
sort coimenrg.dat -o coimenrg.dat
sort coimenve.dat -o coimenve.dat
sort coimesit.dat -o coimesit.dat
sort coimfuge.dat -o coimfuge.dat
sort coimfunp.dat -o coimfunp.dat
sort coimfunz.dat -o coimfunz.dat
sort coimgage.dat -o coimgage.dat
sort coimgend.dat -o coimgend.dat
sort coiminco.dat -o coiminco.dat
sort coiminst.dat -o coiminst.dat
sort coimmanu.dat -o coimmanu.dat
sort coimmenp.dat -o coimmenp.dat
sort coimmenu.dat -o coimmenu.dat
sort coimmovi.dat -o coimmovi.dat
sort coimmtar.dat -o coimmtar.dat
sort coimogge.dat -o coimogge.dat
sort coimopdi.dat -o coimopdi.dat
sort coimopve.dat -o coimopve.dat
sort coimpote.dat -o coimpote.dat
sort coimprof.dat -o coimprof.dat
sort coimprog.dat -o coimprog.dat
sort coimprov.dat -o coimprov.dat
sort coimprvv.dat -o coimprvv.dat
sort coimqrar.dat -o coimqrar.dat
sort coimregi.dat -o coimregi.dat
sort coimrelg.dat -o coimrelg.dat
sort coimrelt.dat -o coimrelt.dat
sort coimrgen.dat -o coimrgen.dat
sort coimrgh.dat  -o coimrgh.dat
sort coimrife.dat -o coimrife.dat
sort coimruol.dat -o coimruol.dat
sort coimsett.dat -o coimsett.dat
sort coimstpm.dat -o coimstpm.dat
sort coimstub.dat -o coimstub.dat
sort coimtano.dat -o coimtano.dat
sort coimtari.dat -o coimtari.dat
sort coimtcar.dat -o coimtcar.dat
sort coimtdoc.dat -o coimtdoc.dat
sort coimtgen.dat -o coimtgen.dat
sort coimtodo.dat -o coimtodo.dat
sort coimtopo.dat -o coimtopo.dat
sort coimtpbo.dat -o coimtpbo.dat
sort coimtpdu.dat -o coimtpdu.dat
sort coimtpem.dat -o coimtpem.dat
sort coimtpim.dat -o coimtpim.dat
sort coimtppr.dat -o coimtppr.dat
sort coimutar.dat -o coimutar.dat
sort coimuten.dat -o coimuten.dat
sort coimutgi.dat -o coimutgi.dat
sort coimviae.dat -o coimviae.dat
sort coimviar.dat -o coimviar.dat
