--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimsett
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(ID_SETTORE                    CHAR(20) NULLIF (ID_SETTORE = BLANKS)
,DESCRIZIONE                   CHAR(50) NULLIF (DESCRIZIONE = BLANKS)
,RESPONSABILE                  CHAR(10) NULLIF (RESPONSABILE = BLANKS)
)
