--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimtpbo
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_TPBO                      CHAR(2) NULLIF (COD_TPBO = BLANKS)
,DESCR_TPBO                    CHAR(20) NULLIF (DESCR_TPBO = BLANKS)
)
