--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimenrg
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_RGEN                      CHAR(8) NULLIF (COD_RGEN = BLANKS)
,COD_ENRE                      CHAR(8) NULLIF (COD_ENRE = BLANKS)
)
