--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimviae
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_VIA                       CHAR(8) NULLIF (COD_VIA = BLANKS)
,COD_COMUNE                    CHAR(8) NULLIF (COD_COMUNE = BLANKS)
,DESCRIZIONE                   CHAR(50) NULLIF (DESCRIZIONE = BLANKS)
,DESCR_TOPO                    CHAR(50) NULLIF (DESCR_TOPO = BLANKS)
,DESCR_ESTESA                  CHAR(50) NULLIF (DESCR_ESTESA = BLANKS)
)
