--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimanrg
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_TANO                      CHAR(8) NULLIF (COD_TANO = BLANKS)
,COD_RGEN                      CHAR(8) NULLIF (COD_RGEN = BLANKS)
)
