--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimtpem
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_EMISSIONE                 CHAR(8) NULLIF (COD_EMISSIONE = BLANKS)
,DESCR_EMISSIONE               CHAR(35) NULLIF (DESCR_EMISSIONE = BLANKS)
,DATA_INS                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_INS = BLANKS)
,DATA_MOD                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_MOD = BLANKS)
,UTENTE                        CHAR(10) NULLIF (UTENTE = BLANKS)
)
