--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimtpsg
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(TIPO_SOGGETTO                 CHAR(1) NULLIF (TIPO_SOGGETTO = BLANKS)
,DESCRIZIONE                   CHAR(100) NULLIF (DESCRIZIONE = BLANKS)
)
