--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimtpim
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_TPIM                      CHAR(8) NULLIF (COD_TPIM = BLANKS)
,DESCR_TPIM                    CHAR(35) NULLIF (DESCR_TPIM = BLANKS)
,DATA_INS                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_INS = BLANKS)
,DATA_MOD                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_MOD = BLANKS)
,UTENTE                        CHAR(10) NULLIF (UTENTE = BLANKS)
)
