--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimtcar
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_AREA                      CHAR(8) NULLIF (COD_AREA = BLANKS)
,COD_OPVE                      CHAR(8) NULLIF (COD_OPVE = BLANKS)
,DATA_INS                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_INS = BLANKS)
,DATA_MOD                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_MOD = BLANKS)
,UTENTE                        CHAR(10) NULLIF (UTENTE = BLANKS)
)
