--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimopdi
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_OPVE                      CHAR(8) NULLIF (COD_OPVE = BLANKS)
,PROG_DISP                     DECIMAL EXTERNAL(3) NULLIF (PROG_DISP = BLANKS)
,ORA_DA                        CHAR(8) NULLIF (ORA_DA = BLANKS)
,ORA_A                         CHAR(8) NULLIF (ORA_A = BLANKS)
)
