--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimtpdo
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_TPDO                      CHAR(8) NULLIF (COD_TPDO = BLANKS)
,DESCRIZIONE                   CHAR(50) NULLIF (DESCRIZIONE = BLANKS)
,FLAG_MODIFICA                 CHAR(1) NULLIF (FLAG_MODIFICA = BLANKS)
)
