--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimrgh
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(RGH_CDE                       DECIMAL EXTERNAL(4) NULLIF (RGH_CDE = BLANKS)
)
