--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimfunp
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(NOME_FUNZ                     CHAR(50) NULLIF (NOME_FUNZ = BLANKS)
,DESC_FUNZ                     CHAR(60) NULLIF (DESC_FUNZ = BLANKS)
)
