--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimcurb
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_URB                       CHAR(8) NULLIF (COD_URB = BLANKS)
,COD_COMUNE                    CHAR(8) NULLIF (COD_COMUNE = BLANKS)
,DESCRIZIONE                   CHAR(50) NULLIF (DESCRIZIONE = BLANKS)
)
