--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimmenp
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(NOME_MENU                     CHAR(20) NULLIF (NOME_MENU = BLANKS)
,DESCRIZIONE                   CHAR(60) NULLIF (DESCRIZIONE = BLANKS)
)
