--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimcomb
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_COMBUSTIBILE              CHAR(8) NULLIF (COD_COMBUSTIBILE = BLANKS)
,DESCR_COMB                    CHAR(35) NULLIF (DESCR_COMB = BLANKS)
,DATA_INS                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_INS = BLANKS)
,DATA_MOD                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_MOD = BLANKS)
,UTENTE                        CHAR(10) NULLIF (UTENTE = BLANKS)
)
