--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimlist
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_LISTINO                   CHAR(8) NULLIF (COD_LISTINO = BLANKS)
,DESCRIZIONE                   CHAR(50) NULLIF (DESCRIZIONE = BLANKS)
)
