--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimanec
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_ENRE                      CHAR(8) NULLIF (COD_ENRE = BLANKS)
,COD_CIMP                      CHAR(8) NULLIF (COD_CIMP = BLANKS)
,TESTO_ANOM                    CHAR(4000) NULLIF (TESTO_ANOM = BLANKS)
)
