--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimrgen
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_RGEN                      CHAR(8) NULLIF (COD_RGEN = BLANKS)
,DESCRIZIONE                   CHAR(100) NULLIF (DESCRIZIONE = BLANKS)
)
