--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimutgi
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_UTGI                      CHAR(8) NULLIF (COD_UTGI = BLANKS)
,DESCR_UTGI                    CHAR(50) NULLIF (DESCR_UTGI = BLANKS)
,DATA_INS                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_INS = BLANKS)
,DATA_MOD                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_MOD = BLANKS)
,UTENTE                        CHAR(10) NULLIF (UTENTE = BLANKS)
)
