--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimtpdu
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_TPDU                      CHAR(8) NULLIF (COD_TPDU = BLANKS)
,DESCR_TPDU                    CHAR(50) NULLIF (DESCR_TPDU = BLANKS)
,DATA_INS                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_INS = BLANKS)
,DATA_MOD                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_MOD = BLANKS)
,UTENTE                        CHAR(10) NULLIF (UTENTE = BLANKS)
)
