--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET UTF8
INTO TABLE coimtopo
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_TOPO                      CHAR(8) NULLIF (COD_TOPO = BLANKS)
,DESCR_TOPO                    CHAR(50) NULLIF (DESCR_TOPO = BLANKS)
)
