drop trigger trig_coimgend_st on coimgend;
create or replace function coimgend_st_tr() returns trigger
as '
declare
st_ope coimgend_st.st_operazione%TYPE;
begin
IF (TG_OP = ''DELETE'') THEN
	 st_ope := ''C'';
 END IF;
IF (TG_OP = ''UPDATE'') THEN
	 st_ope := ''M'';
 END IF;
IF (TG_OP = ''INSERT'') THEN
	 st_ope = ''I'';
 END IF;
--
IF (TG_OP = ''UPDATE'') or  (TG_OP = ''DELETE'') THEN 
insert into coimgend_st (
 cod_impianto,   
 gen_prog,    
 descrizione,   
 matricola, 
 modello,     
 cod_cost,   
 matricola_bruc,   
 modello_bruc, 
 cod_cost_bruc,  
 tipo_foco,   
 mod_funz,       
 cod_utgi,        
 tipo_bruciatore,    
 tiraggio,    
 locale,  
 cod_emissione,   
 cod_combustibile,  
 data_installaz,   
 data_rottamaz,   
 pot_focolare_lib, 
 pot_utile_lib,  
 pot_focolare_nom,  
 pot_utile_nom,      
 flag_attivo, 
 note,           
 data_ins,            
 data_mod,            
 utente,              
 gen_prog_est,        
 data_costruz_gen,    
 data_costruz_bruc,   
 data_installaz_bruc, 
 data_rottamaz_bruc,  
 marc_effic_energ,   
 campo_funzion_min,   
 campo_funzion_max,  
 dpr_660_96, 
 utente_ins,
 igni_progressivo,
 portata_comb,
 portata_termica,
 --st_progressivo,
 st_utente,
 st_operazione,
 st_data_validita          
        )  values (
 OLD.cod_impianto,   
 OLD.gen_prog,    
 OLD.descrizione,   
 OLD.matricola, 
 OLD.modello,     
 OLD.cod_cost,   
 OLD.matricola_bruc,   
 OLD.modello_bruc, 
 OLD.cod_cost_bruc,  
 OLD.tipo_foco,   
 OLD.mod_funz,       
 OLD.cod_utgi,        
 OLD.tipo_bruciatore,    
 OLD.tiraggio,    
 OLD.locale,  
 OLD.cod_emissione,   
 OLD.cod_combustibile,  
 OLD.data_installaz,   
 OLD.data_rottamaz,   
 OLD.pot_focolare_lib, 
 OLD.pot_utile_lib,  
 OLD.pot_focolare_nom,  
 OLD.pot_utile_nom,      
 OLD.flag_attivo, 
 OLD.note,           
 OLD.data_ins,            
 OLD.data_mod,            
 OLD.utente,              
 OLD.gen_prog_est,        
 OLD.data_costruz_gen,    
 OLD.data_costruz_bruc,   
 OLD.data_installaz_bruc, 
 OLD.data_rottamaz_bruc,  
 OLD.marc_effic_energ,   
 OLD.campo_funzion_min,   
 OLD.campo_funzion_max,  
 OLD.dpr_660_96, 
 OLD.utente_ins,
 OLD.igni_progressivo,
 OLD.portata_comb,
 OLD.portata_termica,
 --null,
 NEW.utente,
 st_ope, 
 current_timestamp
 );
insert into coimaimp_st(
		cod_impianto, 
	     	cod_impianto_est,
		cod_impianto_prov,
		descrizione,
		provenienza_dati,
		cod_combustibile,
		cod_potenza,
		potenza,
		potenza_utile,
		data_installaz,
		data_attivaz,
		data_rottamaz,
		note,
		stato,
		flag_dichiarato,
		data_prima_dich,
		data_ultim_dich,
		cod_tpim,
		consumo_annuo,
		n_generatori,
		stato_conformita,
		cod_cted,
		tariffa,
		cod_responsabile,
		flag_resp,
		cod_intestatario,
		flag_intestatario,
		cod_proprietario,
		cod_occupante,
		cod_amministratore,
		cod_manutentore,
		cod_installatore,
		cod_distributore,
		cod_progettista,
		cod_amag,
		cod_ubicazione,
		localita,
		cod_via,
		toponimo,
		indirizzo,
		numero,
		esponente,
		scala,
		piano,
		interno,
		cod_comune,
		cod_provincia,
		cap,
--		cod_catasto,
		cod_tpdu,
		cod_qua,
		cod_urb,
		data_ins,
		data_mod,
		utente,
		flag_dpr412,
		cod_impianto_dest,
		anno_costruzione,
		marc_effic_energ,
		volimetria_risc,
		gb_x,
		gb_y,
		data_scad_dich,
		flag_coordinate,
		flag_targa_stampata,
		cod_impianto_old,
		portata,
		palazzo,
		n_unita_immob,
		cod_tipo_attivita,
		adibito_a,
		utente_ins,
		igni_progressivo,
              cod_iterman,
              circuito_primario,
              distr_calore,
              n_scambiatori,
              potenza_scamb_tot,
              nome_rete,
              cod_alim,
              cod_fdc,
              note_dest,
              cop,
              per,
		st_utente,
 		st_operazione, 
 		st_data_validita) 

		select cod_impianto, 
	     	cod_impianto_est,
		cod_impianto_prov,
		descrizione,
		provenienza_dati,
		cod_combustibile,
		cod_potenza,
		potenza,
		potenza_utile,
		data_installaz,
		data_attivaz,
		data_rottamaz,
		note,
		stato,
		flag_dichiarato,
		data_prima_dich,
		data_ultim_dich,
		cod_tpim,
		consumo_annuo,
		n_generatori,
		stato_conformita,
		cod_cted,
		tariffa,
		cod_responsabile,
		flag_resp,
		cod_intestatario,
		flag_intestatario,
		cod_proprietario,
		cod_occupante,
		cod_amministratore,
		cod_manutentore,
		cod_installatore,
		cod_distributore,
		cod_progettista,
		cod_amag,
		cod_ubicazione,
		localita,
		cod_via,
		toponimo,
		indirizzo,
		numero,
		esponente,
		scala,
		piano,
		interno,
		cod_comune,
		cod_provincia,
		cap,
--		cod_catasto,
		cod_tpdu,
		cod_qua,
		cod_urb,
		data_ins,
		data_mod,
		utente,
		flag_dpr412,
		cod_impianto_dest,
		anno_costruzione,
		marc_effic_energ,
		volimetria_risc,
		gb_x,
		gb_y,
		data_scad_dich,
		flag_coordinate,
		flag_targa_stampata,
		cod_impianto_old,
		portata,
		palazzo,
		n_unita_immob,
		cod_tipo_attivita,
		adibito_a,
		utente_ins,
		igni_progressivo,
              cod_iterman,
              circuito_primario,
              distr_calore,
              n_scambiatori,
              potenza_scamb_tot,
              nome_rete,
              cod_alim,
              cod_fdc,
              note_dest,
              cop,
              per,
 		NEW.utente,st_ope,current_timestamp from coimaimp where cod_impianto = OLD.cod_impianto;
END IF;
  return new;
end;
' language 'plpgsql';
create trigger trig_coimgend_st after update on coimgend
for each row
execute procedure coimgend_st_tr ();

   
 

