#!/bin/sh 

# give time for Postgres to come up
sleep 4

exec /usr/local/aolserver/bin/nsd-postgres -it /var/lib/aolserver/ucit/etc/config.tcl -u nsadmin -g web -b 192.168.235.5:80

# For AOLserver 4 using privileged ports (usually < 1024), add the flag
# -b youraddress:yourport
