--OPTIONS(DIRECT=TRUE)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE coimcted
REPLACE
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(COD_CTED                      CHAR(8) NULLIF (COD_CTED = BLANKS)
,DESCR_CTED                    CHAR(150) NULLIF (DESCR_CTED = BLANKS)
,DATA_INS                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_INS = BLANKS)
,DATA_MOD                      DATE(10) "YYYY-MM-DD" NULLIF (DATA_MOD = BLANKS)
,UTENTE                        CHAR(10) NULLIF (UTENTE = BLANKS)
)
